---
default_set: 'centos-64-x64'
sets:
  'centos-59-x64':
    nodes:
      "main":
        prefab: 'centos-59-x64'
        options:
          cpus: 4
  'centos-64-x64':
    nodes:
      "main":
        prefab: 'centos-64-x64'
        options:
          cpus: 4
  'fedora-18-x64':
    nodes:
      "main":
        prefab: 'fedora-18-x64'
        options:
          cpus: 4
  'debian-607-x64':
    nodes:
      "main":
        prefab: 'debian-607-x64'
        options:
          cpus: 4
  'debian-70rc1-x64':
    nodes:
      "main":
        prefab: 'debian-70rc1-x64'
        options:
          cpus: 4
  'ubuntu-server-12042-x64':
    nodes:
      "main":
        prefab: 'ubuntu-server-12042-x64'
        options:
          cpus: 4
  'sles-11sp1-x64':
    nodes:
      "main":
        prefab: 'sles-11sp1-x64'
        options:
          cpus: 4
