language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_GEM_VERSION="2.7.14"
  - PUPPET_GEM_VERSION="~> 2.7"
  - PUPPET_GEM_VERSION="~> 3.3"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="2.7.14"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="2.7.14"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7"
notifications:
  email: false
