sudo: false
language: ruby
bundler_args: --without beaker
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
env:
  - PUPPET_GEM_VERSION="~> 3.3"
  - PUPPET_GEM_VERSION="~> 3.7" FUTURE_PARSER="yes"
matrix:
  fast_finish: true
notifications:
  email: false
