name    'jhoblitt-irqbalance'
version '1.1.0'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-irqbalance'
source 'https://github.com/jhoblitt/puppet-irqbalance.git'
summary 'manages the irqbalance package'
description 'manages the irqbalance package'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
